In [1]:
import pandas as pd

df = pd.read_csv("focos_mensal_br_202604.csv")
df.head()

,id,lat,lon,data_hora_gmt,satelite,municipio,estado,pais,municipio_id,estado_id,pais_id,numero_dias_sem_chuva,precipitacao,risco_fogo,bioma,frp
0,4f6a0364-e151-3899-8f9d-cbb3178a89c7,-22.48731,-51.67123,2026-04-01 00:37:00,TERRA_M-M,ESTRELA DO NORTE,SÃO PAULO,Brasil,3515301,35,33,6,6.24,0.33,Mata Atlântica,7.6
1,e1a6ec46-f800-3a93-ba3e-1b1f08710a09,-21.60345,-56.62579,2026-04-01 00:37:00,TERRA_M-M,BELA VISTA,MATO GROSSO DO SUL,Brasil,5002100,50,33,3,1.94,0.09,Cerrado,24.5
2,f66745e6-9f53-3262-8fc7-f313cfb7dd6a,-20.03939,-54.50789,2026-04-01 00:37:00,TERRA_M-M,JARAGUARI,MATO GROSSO DO SUL,Brasil,5004908,50,33,0,0.01,0.17,Cerrado,8.3
3,07ee5df2-51cc-3d15-9e16-cb2c5f76a4c8,-20.04072,-54.51852,2026-04-01 00:37:00,TERRA_M-M,JARAGUARI,MATO GROSSO DO SUL,Brasil,5004908,50,33,0,0.00,0.14,Cerrado,16.7
4,f74285dc-5e81-345e-95ec-839d2c090724,-14.44613,-58.43882,2026-04-01 00:39:00,TERRA_M-M,TANGARÁ DA SERRA,MATO GROSSO,Brasil,5107958,51,33,2,4.03,0.03,Cerrado,18.1

In [2]:
df.columns

Index(['id', 'lat', 'lon', 'data_hora_gmt', 'satelite', 'municipio', 'estado',
       'pais', 'municipio_id', 'estado_id', 'pais_id', 'numero_dias_sem_chuva',
       'precipitacao', 'risco_fogo', 'bioma', 'frp'],
      dtype='str')

In [3]:
from sqlalchemy import create_engine

engine = create_engine("postgresql://postgres:123@localhost:5432/focosdb")

In [4]:
import pandas as pd

pd.read_sql("SELECT version();", engine)

                                             version
0  PostgreSQL 14.2, compiled by Visual C++ build ...

In [5]:
df_reduzido = df[['id', 'lat', 'lon', 'data_hora_gmt', 'municipio', 'estado', 'bioma']]
df_reduzido.head()

,id,lat,lon,data_hora_gmt,municipio,estado,bioma
0,4f6a0364-e151-3899-8f9d-cbb3178a89c7,-22.48731,-51.67123,2026-04-01 00:37:00,ESTRELA DO NORTE,SÃO PAULO,Mata Atlântica
1,e1a6ec46-f800-3a93-ba3e-1b1f08710a09,-21.60345,-56.62579,2026-04-01 00:37:00,BELA VISTA,MATO GROSSO DO SUL,Cerrado
2,f66745e6-9f53-3262-8fc7-f313cfb7dd6a,-20.03939,-54.50789,2026-04-01 00:37:00,JARAGUARI,MATO GROSSO DO SUL,Cerrado
3,07ee5df2-51cc-3d15-9e16-cb2c5f76a4c8,-20.04072,-54.51852,2026-04-01 00:37:00,JARAGUARI,MATO GROSSO DO SUL,Cerrado
4,f74285dc-5e81-345e-95ec-839d2c090724,-14.44613,-58.43882,2026-04-01 00:39:00,TANGARÁ DA SERRA,MATO GROSSO,Cerrado

In [6]:
df_reduzido['data_hora_gmt'] = pd.to_datetime(df_reduzido['data_hora_gmt'])

In [7]:
df_reduzido.to_sql(
    "focos",
    engine,
    if_exists="append",
    index=False
)

736

In [8]:
pip install flask

Requirement already satisfied: flask in c:\users\lab-48\appdata\local\programs\python\python313\lib\site-packages (3.1.3)
Requirement already satisfied: blinker>=1.9.0 in c:\users\lab-48\appdata\local\programs\python\python313\lib\site-packages (from flask) (1.9.0)
Requirement already satisfied: click>=8.1.3 in c:\users\lab-48\appdata\local\programs\python\python313\lib\site-packages (from flask) (8.4.1)
Requirement already satisfied: itsdangerous>=2.2.0 in c:\users\lab-48\appdata\local\programs\python\python313\lib\site-packages (from flask) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in c:\users\lab-48\appdata\local\programs\python\python313\lib\site-packages (from flask) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in c:\users\lab-48\appdata\local\programs\python\python313\lib\site-packages (from flask) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in c:\users\lab-48\appdata\local\programs\python\python313\lib\site-packages (from flask) (3.1.8)
Requirement already satisfied: colorama in c:\users\lab-48\appdata\local\programs\python\python313\lib\site-packages (from click>=8.1.3->flask) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
import os

os.makedirs("templates", exist_ok=True)
os.makedirs("static", exist_ok=True)

In [10]:
%%writefile templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Mapa de Focos de Calor</title>

    <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css"/>
    <link rel="stylesheet" href="https://unpkg.com/leaflet-draw/dist/leaflet.draw.css"/>

    <style>
        #map {
            height: 90vh;
            width: 100%;
        }
    </style>
</head>
<body>

    <h2>Mapa de Focos de Calor</h2>
    <div id="map"></div>

    <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
    <script src="https://unpkg.com/leaflet-draw/dist/leaflet.draw.js"></script>

    <script>
        var map = L.map('map').setView([-14.235, -51.925], 4);

        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '© OpenStreetMap'
        }).addTo(map);

        var drawnItems = new L.FeatureGroup();
        map.addLayer(drawnItems);

        var drawControl = new L.Control.Draw({
            draw: {
                polygon: true,
                rectangle: true,
                circle: false,
                marker: false,
                polyline: false,
                circlemarker: false
            },
            edit: {
                featureGroup: drawnItems
            }
        });

        map.addControl(drawControl);

        map.on(L.Draw.Event.CREATED, function (e) {
            var layer = e.layer;
            drawnItems.addLayer(layer);

            var latlngs = layer.getLatLngs()[0];
            var coordinates = latlngs.map(function(point) {
                return [point.lng, point.lat];
            });

            fetch("/contar", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: JSON.stringify({
                    coordinates: coordinates
                })
            })
            .then(response => response.json())
            .then(data => {
                alert("Número de focos na área: " + data.quantidade);
            });
        });
    </script>

</body>
</html>

Overwriting templates/index.html

In [11]:
%%writefile app.py
from flask import Flask, render_template, request, jsonify
from sqlalchemy import create_engine, text

app = Flask(__name__)

engine = create_engine("postgresql://postgres:123@localhost:5432/focosdb")

@app.route("/")
def home():
    return render_template("index.html")

@app.route("/contar", methods=["POST"])
def contar():
    dados = request.json
    coordenadas = dados["coordinates"]

    coords_text = ", ".join([f"{lon} {lat}" for lon, lat in coordenadas])
    coords_text += f", {coordenadas[0][0]} {coordenadas[0][1]}"

    wkt = f"POLYGON(({coords_text}))"

    query = text(f"""
        SELECT COUNT(*)
        FROM focos
        WHERE ST_Contains(
            ST_GeomFromText(:wkt, 4326),
            geom
        );
    """)

    with engine.connect() as conn:
        resultado = conn.execute(query, {"wkt": wkt}).scalar()

    return jsonify({"quantidade": resultado})

if __name__ == "__main__":
    app.run(debug=True)

Overwriting app.py

In [ ]:
!python app.py